# Generated by Django 3.2 on 2021-04-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodoorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Bag',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag.bag')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodoorapp.item')),
            ],
            options={
                'db_table': 'BagItem',
            },
        ),
    ]
